### ISSUE TITLE
Troubles importing modules (for example: Utilities)

### ISSUE THREAD

**Issue by adanielpincab** [HourGlss/HourCrypto#3]
Testing a new feature that I implemented, the following error appears when trying to run Wallet.py:
```
Traceback (most recent call last):
  File "Wallet.py", line 26, in <module>
    from Utilities.Utility import get_data_from_file, gen_encryption_key
ModuleNotFoundError: No module named 'Utilities'
```

I noticed that running the file in a separate subfolder leads to that problem. (Importing Utilities being in the same folder that the module can be done without problem)

Of course, the solution for this is running the script in the same directory where the module is. But this can only be done in two ways:
* Moving Wallet.py to the parent folder, where the module is. The problem is that if I must move to the parent folder all the python scripts that use the modules, I'll end up breaking the initial and clean structure of the proyect.
* "If Mohammed doesn't go to the mountain then the mountain must go to Mohammed"... The second option is moving the module to the folder where Wallet.py is. But obviously, it won't be still accesible by other scripts that require it, and if we moved them also to the same folder we would end up in the same mess that in case one.

So... **What can I do?**

**Comment by HourGlss** [comment]
Yes, Like i said in the other issue, this branch is currently in development and is NOT functional. Once I get to functional Ill branch it and dev on a different branch.
